### ISSUE TITLE
Configure voidfactions

### ISSUE THREAD

**Issue by WelshBanana** [Centurion-Networks/ImperialRP#15]

**Comment by WelshBanana** [comment]
Ranks, factions and sub factions have been made. In addition I've added the default rank and faction. Further configuration is need ed for individuals faction ranks.

**Comment by Duck143** [comment]
Seen no worries should get tha sorted tonight, is it ok now to continue with the keycards

**Comment by WelshBanana** [comment]
> Seen no worries should get tha sorted tonight, is it ok now to continue with the keycards

Yeah, we're okay to start on that now just ensure that you whitelist the factions, not the job categories.
