### ISSUE TITLE
Realistic_Police not working

### ISSUE THREAD

**Issue by WelshBanana** [Centurion-Networks/ImperialRP#22]
**Describe the bug**
Addon is not working failing to start up due to the way jobs are listed. (addons/realistic_police/lua/realistic_police/sh_rpt_config.lua:51)

**Expected behavior**
Should work fine, but doesn't.

**Comment by Duck143** [comment]
I'll have a loook at this later on today I got a funny feeling of what it is.  

Duck

**Comment by WelshBanana** [comment]
Fixed this and is now working as intended.
