### ISSUE TITLE
The Grand Inquisitor is an Error on the F4 Menu

### ISSUE THREAD

**Issue by WelshBanana** [Centurion-Networks/ImperialRP#28]
The Grand Inquisitor is an Error on the F4 Menu

_Originally posted by @SPACE02 in https://github.com/Centurion-Networks/ImperialRP/issues/27#issuecomment-1368878387_

**Comment by WelshBanana** [comment]
Need new inquisitor model added, I've already got it in the content pack just needs to be set.

**Comment by Duck143** [comment]
Issue fixed and added to server

Nothing further to add
